function out = Regressor_DRR_sim(in)
%REGRESSOR_DRR
%    Y = REGRESSOR_DRR(Q1,Q2,QD1,QD2,QRD1,QRD2,QRDD1,QRDD2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-May-2020 18:31:01

q1 = in(1);
q2 = in(2);
qd1 = in(3);
qd2= in(4);
qrd1 = in(5);
qrd2 = in(6);
qrdd1 = in(7);
qrdd2 = in(8);



t2 = cos(q1);
t3 = sin(q1);
t4 = q1+q2;
t5 = qrdd1+qrdd2;
t6 = cos(t4);
t7 = sin(t4);
t8 = t2+t6;
t9 = t3+t7;
t10 = t7.*t9;
t11 = t6.*t8;
t12 = t7.*t8;
t13 = t6.*t9;
t14 = t12.*2.0;
t15 = t13.*2.0;
t16 = -t13;
t18 = t10+t11;
t17 = -t15;
t19 = t12+t16;
t20 = t14+t17;
Y = reshape([qrdd1.*(t2.^2+t3.^2),0.0,qrdd1,0.0,qrdd2.*t18-qrd2.*((qd1.*t20)./2.0+(qd2.*t20)./2.0)+qrdd1.*(t8.^2+t9.^2)-(qd2.*qrd1.*t20)./2.0,qrdd1.*t18+qd1.*((qrd1.*t20)./2.0+(qrd2.*t19)./2.0)+qrdd2.*(t6.^2+t7.^2)-(qd1.*qrd2.*t19)./2.0,t5,t5],[2,4]);
out = Y;