function out = Y_Simulink(in)
%RR_REGRESSOR_Y
%    Y = RR_REGRESSOR_Y(Q1,Q2,DQ1,DQ2,DQR1,DQR2,DDQR1,DDQR2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    12-Jun-2020 16:00:25

q1=in(1);
q2=in(2);

dq1=in(3);
dq2=in(4);

dqr1=in(5);
dqr2=in(6);

ddqr1=in(7);
ddqr2=in(8);


t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q2);
t5 = ddqr1+ddqr2;
t6 = dq1+dq2;
t7 = q1+q2;
t8 = t3.*2.0;
t9 = t3+1.0;
t11 = cos(t7);
t12 = dq1.*dqr1.*t4;
t13 = dq2.*dqr1.*t4;
t16 = dqr2.*t4.*t6;
t19 = t2.*(9.81e+2./1.0e+2);
t10 = t9+1.0;
t14 = t8+2.0;
t15 = -t13;
t18 = -t16;
t20 = t11.*(9.81e+2./1.0e+2);
t17 = ddqr1.*t14;
Y = reshape([ddqr1+t19,0.0,ddqr1.*2.0+t19,0.0,ddqr1,0.0,t15+t17+t18+t19+t20+ddqr2.*t9,ddqr2+t12+t20+ddqr1.*t9,t15+t17+t18+t20+ddqr2.*t10,ddqr2.*2.0+t12+t20+ddqr1.*t10,t5,t5],[2,6]);
ouy=Y;